### ISSUE TITLE
ImportError: cannot import name redfish_client

### ISSUE THREAD

**Issue by t2691** [HewlettPackard/ansible-ilorest-role#7]
Trying to get ex11_modify_ilo_user_account.py working. Seems with python-ilorest-library 3.0.installed with pip has some redfish modules missing. 

Is this role still supported and working? It looks like a lot of the examples are not working with iLO 4 in my testing.

**Comment by rajeevkallur** [comment]
Hi,  Please try with latest scripts from ilorest_3.0 branch which work with python-ilorest-library 3.0
[Note that some of the scripts are in development]

**Comment by t2691** [comment]
Can you give some more details? There are multiple scripts in the repos including some legacy rest examples.
Also most of the example scripts in the python-ilorest-library do not have examples in the code.

**Comment by rajeevkallur** [comment]
Please check the library and playbooks/hpe/  directories which have latest scripts.  We are looking to enhance these in the coming days.  Opensource ansible roles like redfish_command, redfish_config and redfish_info can also be used in the playbooks.

**Comment by t2691** [comment]
I don't see redfish_command, redfish_config and redfish_info  anywhere in the HP github. Can you point to where those are located.

Which latest scripts are you talking about, everything in this repo is 3 years old?

**Comment by rajeevkallur** [comment]
Please refer to https://github.com/HewlettPackard/ansible-ilorest-role/tree/ilorest_3.0  for latest scripts

Also, https://github.com/ansible/ansible which has redfish_command, redfish_config and redfish_info.

**Comment by rajeevkallur** [comment]
![image](https://user-images.githubusercontent.com/21117913/80002442-45afa800-84dd-11ea-841b-a2ea3ad7b890.png)

**Comment by rajeevkallur** [comment]
![image](https://user-images.githubusercontent.com/21117913/80002546-67109400-84dd-11ea-8986-92f85525f0d8.png)

**Comment by t2691** [comment]
Thank you for the updates.
